# -*- coding: utf-8 -*-
"""Extract.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KwzVurzy8r_fPwgjAJLZqGZgSiwbBErU

{ "connectionString": "DefaultEndpointsProtocol=https;AccountName=airqualityhw12;AccountKey=V/ecsX6srJNIVVGy6nKLt4LU/939dvFP8BNdMT6LVPnKW9HDZFT/2DSqPVbjR3W7QZDmUi9uSQl6+AStXRqpNg==;
EndpointSuffix=core.windows.net" }
"""

!pip install azure-storage-blob

import pandas as pd
import json
from azure.storage.blob import BlobServiceClient, BlobClient, ContainerClient

#dataset unique identifier
dataset_identifier = "c3uy-2p5r"

#URL to get the data
url = f"https://data.cityofnewyork.us/api/views/{dataset_identifier}/rows.csv?accessType=DOWNLOAD"

#reading the data
df = pd.read_csv(url)
df = df.to_csv(index = False)



config_file_path = 'config.json'
with open(config_file_path, 'r') as config_file:
    config = json.load(config_file)

connection_string_azure_storage = config["connectionString"]

container_name = "airqualityhw12"
blob_name = "airquality_data"

blob_service_client = BlobServiceClient.from_connection_string(connection_string_azure_storage)

blob_client = blob_service_client.get_blob_client(container=container_name, blob=blob_name)

blob_client.upload_blob(df, overwrite=True)



